#server
server:
  port: 10000
#  servlet:
#    session:
#      timeout: 10
#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

  #Redis
  session:
    store-type: redis

#  security:
#    user:
#      name: hds
#      password: 1234

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: MikyiaH7XQCJmKsKPMYQ
            client-secret: hsqzTHjVuV
            redirect-uri: http://localhost:10000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, mobile

          kakao:
            client-name: kakao
            client-id: 360bd80ecf2ad2ca8d84ce4c2d079212
            client-secret: Mizwq0Ro68SIRXHbokPHRO9ZzHy4X0m5
            redirect-uri: http://localhost:10000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname, profile_image

          google:
            client-id: 986108389553-5u7234jptsu096kbs9utqgjq4e9mu7tn.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:10000/login/oauth2/code/google
            scope: email, profile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account












